### ISSUE TITLE
Неправильный порядок тегов

### ISSUE THREAD

**Issue by andrewQwer** [LukashevichDanik/iTechArtLab2016#1]
https://github.com/LukashevichDanik/iTechArtLab2016/blob/master/HTML-CSS-practice/index.html#L33

Spec: https://www.w3.org/TR/html5/grouping-content.html#the-ul-element

`a` тег не может быть child-ом для `ul`, хотя по спеке HTML5 он может содержать внутри себя блочные элементы.

**Comment by LukashevichDanik** [comment]
Fixed
