### ISSUE TITLE
непонятные алерты в тестах

### ISSUE THREAD

**Issue by andrewQwer** [LukashevichDanik/iTechArtLab2016#10]
1)
![image](https://cloud.githubusercontent.com/assets/710513/16374520/795fc150-3c5f-11e6-8769-1b8da262c938.png)
2)
![image](https://cloud.githubusercontent.com/assets/710513/16374541/92c391e4-3c5f-11e6-9201-5474d689d8de.png)
3)
![image](https://cloud.githubusercontent.com/assets/710513/16374551/9fa27dc6-3c5f-11e6-84a7-2a6a1ab308db.png)
4)
![image](https://cloud.githubusercontent.com/assets/710513/16374561/ab761ce8-3c5f-11e6-81d4-3b16857218b6.png)
5)
![image](https://cloud.githubusercontent.com/assets/710513/16374603/df8cdd32-3c5f-11e6-9aae-c5b4793efb41.png)

**Comment by LukashevichDanik** [comment]
исправил
