### ISSUE TITLE
Непонятное использование Number

### ISSUE THREAD

**Issue by andrewQwer** [LukashevichDanik/iTechArtLab2016#12]
Практически везде оборачиваешь цифры в Number, поясни зачем
```
if ((Number(arr1[i]) < Number(arr1[i + 1]))
```

**Comment by LukashevichDanik** [comment]
@andrewQwer  просто не хотел ошибиться в сравнении чисел. Чтобы вместо чисел оно не сравнивало строки. Все исправил
