### ISSUE TITLE
Калькулятор не работает с некоторыми выражениямиё

### ISSUE THREAD

**Issue by andrewQwer** [LukashevichDanik/iTechArtLab2016#16]
1) -3+4
2) 4+(-3)
3) 2+(3*2-6) - перфоманс проблемы, браузер подвисает + ошибки в консоли

**Comment by LukashevichDanik** [comment]
@andrewQwer я исправил калькулятор, теперь операции можно производить с отрицательными числами

**Comment by andrewQwer** [comment]
2+(3*2-1) - высчитывает не правильно )
