### ISSUE TITLE
Много ООП ошибок

### ISSUE THREAD

**Issue by andrewQwer** [LukashevichDanik/iTechArtLab2016#17]
Некорректно используешь ООП в Javascript
1) Если у тебя есть некое свойство, типа `this.string`, то лучше организовать доступ к нему через набор методов `setString(str); getString(str);` а саму переменную спрятать и получать доступ к ней через замыкание. Типа так:
```javascript
function SomeClass() {
var str;
this.getStr = function() {
return str;
}
this.setStr = function(value) {
str = value;
}
...
}
```
2) Часто используешь переменные без объявления
3) Использование замыканий по делу и без:
```
var obj = new MyConverter('',0,0);

function do_task6() {
    var input = document.getElementById('task6_input').value;
    var section_html = document.getElementById('output');
    var from_select = document.getElementById('task6_select_from');
    var from = from_select.options[from_select.selectedIndex].value;
    var to_select = document.getElementById('task6_select_to');
    var to = to_select.options[to_select.selectedIndex].value;
    obj.str = input;
    obj.to = to;
    obj.from = from;
    section_html.innerHTML = 'Результат = ' + obj.convert();
}
```
Зачем делать конструктор с параметрами, если по сути ты их не используешь. Можно было бы создать объект obj внутри метода do_task6() и передать ему значения (input, to, from) при инициализации.

**Comment by LukashevichDanik** [comment]
исправил
