### ISSUE TITLE
Responsive Layout: немного некорректно сделал выравнивание

### ISSUE THREAD

**Issue by andrewQwer** [LukashevichDanik/iTechArtLab2016#3]
Обрати внимание на стили для: header-conteiner__navigation
Ты делаешь отступ сверху 40px; выставляешь vertical-align. Но flexbox позволяет делать это куда элегантнее без всяких отступов.
Примерный фикс:
```
.header-conteiner__navigation {
    display: flex;
    flex-direction: row;
    flex-grow: 1;
    justify-content: flex-end;
}

.header-conteiner__navigation > ul {
    display: flex;
    padding: 0;
    justify-content: flex-end;
    align-items: center;
}
```
Теперь не зависимо от ширины header-conteiner менюшка остается всегда по центру.

**Comment by LukashevichDanik** [comment]
Fixed
